# -*- coding: utf-8 -*-
"""Subtringofstring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sx_5NSMD-3OBSPcrWrBvtzRjigt4F23W
"""

# Python3 program to count number 
# of substrings of a string 
  
def countNonEmptySubstr(str): 
    n = len(str); 
    return int(n * (n + 1) / 2); 
  
# driver code 
s = "abcde"; 
print (countNonEmptySubstr(s));

